### ISSUE TITLE
Please add licensing information

### ISSUE THREAD

**Issue by hartwork** [linuxdeepin/deepin-grub2-themes#1]
Hi, nice theme!

What license is the theme under? Please add licensing information. If you are yet to pick a licenses, let me propose [Creative Commons BY-SA](https://creativecommons.org/licenses/by-sa/4.0/).

Thanks and best, Sebastian

**Comment by fasheng** [comment]
Thanks for your advice, and sorry for the late reply.

License CC-BY-SA was append now. The work for other projects will be dispatched later.

https://github.com/linuxdeepin/deepin-grub2-themes/blob/develop/LICENSE

And you could close the issue for that I do not own such permission.

**Comment by hartwork** [comment]
Very cool, thank you!
Who do we need to get this merged into master?

PS: I ran into [_test/test.sh](https://github.com/linuxdeepin/deepin-grub2-themes/blob/master/_test/test.sh) now. It's basically the exact same thing that I wrote https://github.com/hartwork/grub2-theme-preview some weeks ago when I didn't find a tool to do the job. Please give it a try. I'm happy about bug reports if anything doesn't work as expected.

Best, Sebastian

**Comment by fasheng** [comment]
Great job!
I use `grub2-theme-preview` instead of the `test.sh` now, everything works fine.
Wish the cool tool will be included by the distros soon :)

And about the workflow to merge develop branch into master. I'm afraid it will be done about two months later. For that we are migrating our upstream repositories from ubuntu to debian, and a lot of the code is refectoring in develop branch, so it will take some more time.
